version = 0.1
[default.deploy.parameters]
stack_name = "athena-cloudwatch-metrics"
resolve_s3 = true
s3_prefix = "athena-cloudwatch-metrics"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AthenaCatalogName=\"cloudwatch-metrics\" SpillBucket=\"non-prod-monitoring-athena-cw-505944585706-ap-southeast-1\" SpillPrefix=\"athena-spill\" LambdaTimeout=\"900\" LambdaMemory=\"6000\" DisableSpillEncryption=\"false\" PermissionsBoundaryARN=\"\""
image_repositories = []
